/* ═══════════════════════════════════════════════════════════
   LANG.JS — Multi-language: English / Hebrew / Czech
   Czech Inn Hotels × UNO Platform
   ═══════════════════════════════════════════════════════════ */

const T = {
  en: {
    /* NAV */
    'nav.home':'Home',
    'nav.experiences':'Experiences',
    'nav.col.tours':'Tours & Experiences',
    'nav.guided-tours':'Guided Tours',
    'nav.gold-label':'Gold Label',
    'nav.extras':'Extras Catalogue',
    'nav.after-dark':'Prague After Dark',
    'nav.col.guest':'Guest Experience',
    'nav.concierge':'Digital Concierge',
    'nav.by-passion':'Prague by Passion',
    'nav.corporate':'Groups & Corporate',
    'nav.for-hotels':'For Hotels',
    'nav.col.strategy':'Strategy & Revenue',
    'nav.business-plan':'Business Plan',
    'nav.analytics':'Analytics',
    'nav.col.operations':'Operations & Trust',
    'nav.integration':'Integration',
    'nav.social-proof':'Social Proof',
    'nav.partnership':'Partnership →',
    'nav.badge.premium':'Premium',
    /* FOOTER */
    'footer.desc':'A proposed partnership bringing curated guided tours and premium guest experiences to all 28 Czech Inn Hotels properties across Prague.',
    'footer.address':'Hybernská 24, Praha 1 — 110 00',
    'footer.stats':'28 Hotels · 3,300+ Rooms',
    'footer.col.experiences':'Experiences',
    'footer.col.tools':'Guest Tools',
    'footer.col.hotels':'For Hotels',
    'footer.guided-tours':'Guided Tours',
    'footer.gold-label':'Gold Label',
    'footer.extras':'Extras Catalogue',
    'footer.after-dark':'Prague After Dark',
    'footer.corporate':'Groups & Corporate',
    'footer.concierge':'Digital Concierge',
    'footer.by-passion':'Prague by Passion',
    'footer.integration':'Hotel Integration',
    'footer.business-plan':'Business Plan',
    'footer.analytics':'Analytics',
    'footer.social-proof':'Social Proof',
    'footer.partnership':'Partnership →',
    'footer.tagline':'Guided Experiences Platform — proposed for',
    'footer.prepared':'Prepared for',
    'footer.sub':'All tours, guides, and pricing are real and ready to deploy.',
    'float.cta':'Start the Partnership →',
    /* INDEX */
    'idx.eyebrow':'Czech Inn Hotels × UNO',
    'idx.hero.title':'Prague\'s Guests Are Spending Millions on Experiences.<br><em>None of It Is Going to Czech Inn Hotels.</em>',
    'idx.hero.sub':'Every night, 3,300 guests check into your hotels. Most will book experiences before they leave Prague — just not through you. Until now.',
    'idx.cta.primary':'See the Partnership Plan',
    'idx.cta.secondary':'Explore Experiences',
    'idx.stat1.label':'Partner Hotels',
    'idx.stat2.label':'Rooms Reached',
    'idx.stat3.label':'Tours Ready',
    'idx.stat4.label':'Avg. Guest Rating',
    'idx.why.eyebrow':'Why This Works',
    'idx.why.title':'Prague\'s most-loved hotel group. Prague\'s most trusted tour operator.',
    'idx.rev.eyebrow':'Revenue Impact',
    'idx.rev.title':'Real Numbers. Real Opportunity.',
    'idx.exp.eyebrow':'The Experience Suite',
    'idx.exp.title':'Every Guest. Every Mood. Every Moment.',
    /* AFTER DARK */
    'ad.eyebrow':'Czech Inn Hotels × UNO',
    'ad.title':'Prague<br><em>After Dark</em>',
    'ad.sub':'When the daytime tours end, the real Prague begins. The version most tourists never find — jazz cellars, rooftop bars with castle views, legendary cocktail haunts, and theatres that exist nowhere else on earth.',
    'ad.tab.jazz':'Jazz & Live',
    'ad.tab.rooftop':'Rooftop',
    'ad.tab.cocktail':'Cocktail Bars',
    'ad.tab.shows':'Shows',
    'ad.tab.hidden':'Hidden',
    'ad.filter.all':'All',
    'ad.filter.budget':'€ Budget',
    'ad.filter.mid':'€€ Mid',
    'ad.filter.premium':'€€€ Premium',
    'ad.filter.walkin':'Walk-in OK',
    'ad.filter.book':'Book Required',
    'ad.routes.eyebrow':'Curated Evenings',
    'ad.routes.title':'Three Evenings, Three Moods.',
    'ad.routes.cta':'Book this route →',
    'ad.build.title':'Build Your Night',
    'ad.build.sub':'Pick up to 3 venues',
    'ad.build.cta':'Book via Concierge →',
    'ad.build.clear':'Clear',
    'ad.practical.eyebrow':'Before You Go',
    'ad.practical.title':'What to Know',
    /* CONCIERGE */
    'dc.eyebrow':'Guest Experience Platform',
    'dc.title':'The Concierge Every Guest<br><em>Wished Your Hotel Had</em>',
    'dc.sub':'Your guests arrive expecting a great hotel. They leave raving about the city — because we made Prague feel personal, curated, and effortless for them.',
    'dc.cta':'Try the Concierge',
    /* TOURS */
    'tours.eyebrow':'4 Tours · 12 Languages · 4.91★ Rating',
    'tours.title':'Four Stories Prague Has<br><em>Never Told Quite Like This</em>',
    'tours.sub':'Every stop chosen deliberately. Every story told by someone who\'s spent their life here. Every tour rated 4.91 stars by guests who came back to the hotel talking.',
    'tours.cta':'Book a Tour',
    /* GOLD LABEL */
    'gl.eyebrow':'Czech Inn Hotels — Premium Tier',
    'gl.title':'Gold<br><em>Label</em>',
    'gl.sub':'Curated. Private. Unmistakable.',
    /* EXTRAS */
    'ex.eyebrow':'Czech Inn Hotels Experiences',
    'ex.title':'26 Experiences <em>Prague Will Remember You For</em>',
    'ex.sub':'26 hand-picked Prague experiences — from private cooking classes to helicopter flights. From €29 to €249. Book individually or bundle with any guided tour.',
    /* BUSINESS PLAN */
    'bp.eyebrow':'Business Plan',
    'bp.title':'Business Plan —<br><em>Czech Inn Hotels</em><br>Guided Experiences Platform',
    'bp.sub':'Conservative projections. Proven model. Ready to deploy.',
    /* PARTNERSHIP */
    'pp.eyebrow':'Partnership',
    'pp.title':'The Partnership That<br><em>Pays for Itself</em> — Before<br>It Costs You Anything',
    'pp.sub':'28 hotels. 3,300 rooms. Every guest arriving in Prague with money to spend on experiences — and nowhere to spend it. Until now.',
    'pp.cta':'Start the Conversation',
    /* BY PASSION */
    'byp.eyebrow':'Czech Inn Hotels',
    'byp.title':'Prague <em>by Passion</em>',
    'byp.sub':'Answer four questions. Get a personalised Prague itinerary built around what you actually love — not what everyone else does.',
    /* CORPORATE */
    'corp.eyebrow':'Groups & Corporate',
    'corp.title':'When Your Team Leaves Prague,<br><em>They Leave Different.</em>',
    'corp.sub':'The easiest brief your executive assistant will ever send you. Incentive trips, team building, retreats, and conference extensions — from 10 to 200 people, all built around Czech Inn Hotels properties.',
    /* INTEGRATION */
    'int.eyebrow':'Hotel Integration',
    'int.title':'Zero Friction.<br><em>Zero Downtime.</em>',
    'int.sub':'The entire platform integrates with your hotel operations in under 30 days — no PMS disruption, no dedicated IT resource, no staff retraining.',
    /* ANALYTICS */
    'an.eyebrow':'Performance Dashboard',
    'an.title':'The Numbers That Tell You<br><em>Exactly What You\'re Missing</em>',
    'an.sub':'Real data from Prague tourism 2024. Projected data modelled on Czech Inn Hotels occupancy and comparable partnership benchmarks. All sources cited.',
    /* SOCIAL PROOF */
    'sp.eyebrow':'Verified by Guests',
    'sp.title':'847 Guests. 4.91 Stars.<br><em>Here Is What They Actually Said.</em>',
    'sp.sub':'412 verified reviews. 847 tours completed in 2024. A platform guests recommend to friends — and that drives repeat hotel bookings.',
    /* COMMON */
    'cta.concierge':'Reserve via Concierge →',
    'cta.learn-more':'Learn More →',
    'cta.view-all':'View All →',
    'cta.partnership':'Start the Partnership →',
    'label.new':'New',
    'label.popular':'Popular',
    'label.premium':'Premium',
    'label.free':'Free',
  },

  he: {
    /* NAV */
    'nav.home':'דף הבית',
    'nav.experiences':'חוויות',
    'nav.col.tours':'סיורים וחוויות',
    'nav.guided-tours':'סיורים מודרכים',
    'nav.gold-label':'תווית זהב',
    'nav.extras':'קטלוג תוספות',
    'nav.after-dark':'פראג אחרי החשיכה',
    'nav.col.guest':'חוויית האורח',
    'nav.concierge':'קונסיירז׳ דיגיטלי',
    'nav.by-passion':'פראג לפי תשוקה',
    'nav.corporate':'קבוצות ועסקים',
    'nav.for-hotels':'למלונות',
    'nav.col.strategy':'אסטרטגיה והכנסות',
    'nav.business-plan':'תוכנית עסקית',
    'nav.analytics':'ניתוח נתונים',
    'nav.col.operations':'תפעול ואמינות',
    'nav.integration':'אינטגרציה',
    'nav.social-proof':'המלצות',
    'nav.partnership':'שותפות ←',
    'nav.badge.premium':'פרמיום',
    /* FOOTER */
    'footer.desc':'שותפות מוצעת המביאה סיורים מודרכים וחוויות אורחים פרמיום לכל 28 מלוני Czech Inn Hotels בפראג.',
    'footer.address':'Hybernská 24, Praha 1 — 110 00',
    'footer.stats':'28 מלונות · 3,300+ חדרים',
    'footer.col.experiences':'חוויות',
    'footer.col.tools':'כלים לאורחים',
    'footer.col.hotels':'למלונות',
    'footer.guided-tours':'סיורים מודרכים',
    'footer.gold-label':'תווית זהב',
    'footer.extras':'קטלוג תוספות',
    'footer.after-dark':'פראג אחרי החשיכה',
    'footer.corporate':'קבוצות ועסקים',
    'footer.concierge':'קונסיירז׳ דיגיטלי',
    'footer.by-passion':'פראג לפי תשוקה',
    'footer.integration':'אינטגרציית מלון',
    'footer.business-plan':'תוכנית עסקית',
    'footer.analytics':'ניתוח נתונים',
    'footer.social-proof':'המלצות',
    'footer.partnership':'שותפות ←',
    'footer.tagline':'פלטפורמת חוויות מודרכות — מוצעת ל',
    'footer.prepared':'הוכן עבור',
    'footer.sub':'כל הסיורים, המדריכים והמחירים אמיתיים ומוכנים לפריסה.',
    'float.cta':'התחילו את השותפות ←',
    /* INDEX */
    'idx.eyebrow':'Czech Inn Hotels × UNO',
    'idx.hero.title':'אורחי פראג מוציאים מיליונים על חוויות.<br><em>אף אגורה לא הולכת ל-Czech Inn Hotels.</em>',
    'idx.hero.sub':'כל לילה, 3,300 אורחים מגיעים למלונות שלכם. רובם יזמינו חוויות לפני שיעזבו את פראג — רק לא דרככם. עד עכשיו.',
    'idx.cta.primary':'ראה את תוכנית השותפות',
    'idx.cta.secondary':'גלה חוויות',
    'idx.stat1.label':'מלוני שותפים',
    'idx.stat2.label':'חדרים נגישים',
    'idx.stat3.label':'סיורים מוכנים',
    'idx.stat4.label':'דירוג אורחים ממוצע',
    'idx.why.eyebrow':'למה זה עובד',
    'idx.why.title':'קבוצת המלונות האהובה ביותר בפראג. מפעיל הסיורים המהימן ביותר בפראג.',
    'idx.rev.eyebrow':'השפעה על הכנסות',
    'idx.rev.title':'מספרים אמיתיים. הזדמנות אמיתית.',
    'idx.exp.eyebrow':'חבילת החוויות',
    'idx.exp.title':'כל אורח. כל מצב רוח. כל רגע.',
    /* AFTER DARK */
    'ad.eyebrow':'Czech Inn Hotels × UNO',
    'ad.title':'פראג<br><em>אחרי החשיכה</em>',
    'ad.sub':'כשסיורי היום מסתיימים, פראג האמיתית מתחילה. הגרסה שרוב התיירים אף פעם לא מוצאים — מרתפי ג׳אז, ברים על הגג עם נוף לטירה, ברי קוקטייל אגדיים ותיאטראות שלא קיימים בשום מקום אחר.',
    'ad.tab.jazz':'ג׳אז ולייב',
    'ad.tab.rooftop':'גג',
    'ad.tab.cocktail':'ברים לקוקטייל',
    'ad.tab.shows':'מופעים',
    'ad.tab.hidden':'מוסתרים',
    'ad.filter.all':'הכל',
    'ad.filter.budget':'€ זול',
    'ad.filter.mid':'€€ בינוני',
    'ad.filter.premium':'€€€ פרמיום',
    'ad.filter.walkin':'כניסה חופשית',
    'ad.filter.book':'הזמנה מראש',
    'ad.routes.eyebrow':'ערבים מאורגנים',
    'ad.routes.title':'שלושה ערבים, שלושה מצבי רוח.',
    'ad.routes.cta':'הזמן מסלול זה ←',
    'ad.build.title':'בנה את הלילה שלך',
    'ad.build.sub':'בחר עד 3 מקומות',
    'ad.build.cta':'הזמן דרך הקונסיירז׳ ←',
    'ad.build.clear':'נקה',
    'ad.practical.eyebrow':'לפני שיוצאים',
    'ad.practical.title':'מה כדאי לדעת',
    /* CONCIERGE */
    'dc.eyebrow':'פלטפורמת חוויות אורחים',
    'dc.title':'הקונסיירז׳ שכל אורח<br><em>רצה שיהיה במלון שלכם</em>',
    'dc.sub':'האורחים שלכם מגיעים עם ציפיות. הם עוזבים כשהם מדברים על העיר — כי הפכנו את פראג לאישית, מאורגנת ונטולת מאמץ עבורם.',
    'dc.cta':'נסה את הקונסיירז׳',
    /* TOURS */
    'tours.eyebrow':'4 סיורים · 12 שפות · דירוג 4.91★',
    'tours.title':'ארבעה סיפורים שפראג<br><em>לא סיפרה כך עד היום</em>',
    'tours.sub':'כל עצירה נבחרה בכוונה. כל סיפור מסופר על ידי מי שחי כאן כל חייו. כל סיור דורג 4.91 כוכבים על ידי אורחים שחזרו למלון וסיפרו.',
    'tours.cta':'הזמן סיור',
    /* GOLD LABEL */
    'gl.eyebrow':'Czech Inn Hotels — רמה פרמיום',
    'gl.title':'Gold<br><em>Label</em>',
    'gl.sub':'מאורגן. פרטי. בלתי נשכח.',
    /* EXTRAS */
    'ex.eyebrow':'חוויות Czech Inn Hotels',
    'ex.title':'26 חוויות <em>שפראג תזכור אתכם בגינן</em>',
    'ex.sub':'26 חוויות פראג נבחרות — מסדנאות בישול פרטיות ועד טיסות במסוק. מ-€29 עד €249. הזמינו בנפרד או שלבו עם כל סיור מודרך.',
    /* BUSINESS PLAN */
    'bp.eyebrow':'תוכנית עסקית',
    'bp.title':'תוכנית עסקית —<br><em>Czech Inn Hotels</em><br>פלטפורמת חוויות מודרכות',
    'bp.sub':'תחזיות שמרניות. מודל מוכח. מוכן לפריסה.',
    /* PARTNERSHIP */
    'pp.eyebrow':'שותפות',
    'pp.title':'השותפות שמשלמת<br><em>על עצמה</em> — לפני<br>שתוציאו שקל',
    'pp.sub':'28 מלונות. 3,300 חדרים. כל אורח שמגיע לפראג עם כסף לבזבז על חוויות — ואין לו איפה. עד עכשיו.',
    'pp.cta':'התחל את השיחה',
    /* BY PASSION */
    'byp.eyebrow':'Czech Inn Hotels',
    'byp.title':'פראג <em>לפי תשוקה</em>',
    'byp.sub':'ענה על ארבע שאלות. קבל מסלול פראג אישי שנבנה סביב מה שאתה באמת אוהב — לא מה שכולם עושים.',
    /* CORPORATE */
    'corp.eyebrow':'קבוצות ועסקים',
    'corp.title':'כשהצוות שלכם עוזב את פראג,<br><em>הוא עוזב שונה.</em>',
    'corp.sub':'הבריף הקל ביותר שהעוזר הבכיר שלכם ישלח. טיולי תמריצים, בניית צוות, נסיגות וכנסים ממושכים — מ-10 עד 200 אנשים, כולם סביב מלוני Czech Inn Hotels.',
    /* INTEGRATION */
    'int.eyebrow':'אינטגרציית מלון',
    'int.title':'אפס חיכוך.<br><em>אפס השבתה.</em>',
    'int.sub':'הפלטפורמה כולה מתאימה לפעולות המלון שלכם תוך פחות מ-30 יום — ללא שיבוש מערכת PMS, ללא משאב IT ייעודי, ללא הכשרה מחדש של הצוות.',
    /* ANALYTICS */
    'an.eyebrow':'לוח בקרה ביצועים',
    'an.title':'המספרים שמספרים לכם<br><em>בדיוק מה אתם מפסידים</em>',
    'an.sub':'נתונים אמיתיים מתיירות פראג 2024. נתונים צפויים המבוססים על תפוסת Czech Inn Hotels ומדדי שותפות דומים. כל המקורות מצוינים.',
    /* SOCIAL PROOF */
    'sp.eyebrow':'מאומת על ידי אורחים',
    'sp.title':'847 אורחים. 4.91 כוכבים.<br><em>הנה מה שהם באמת אמרו.</em>',
    'sp.sub':'412 ביקורות מאומתות. 847 סיורים שהושלמו ב-2024. פלטפורמה שאורחים ממליצים עליה לחברים — ומניעה הזמנות חוזרות למלון.',
    /* COMMON */
    'cta.concierge':'הזמן דרך הקונסיירז׳ ←',
    'cta.learn-more':'למידע נוסף ←',
    'cta.view-all':'צפה בהכל ←',
    'cta.partnership':'התחילו את השותפות ←',
    'label.new':'חדש',
    'label.popular':'פופולרי',
    'label.premium':'פרמיום',
    'label.free':'חינם',
  },

  cs: {
    /* NAV */
    'nav.home':'Domů',
    'nav.experiences':'Zážitky',
    'nav.col.tours':'Prohlídky a zážitky',
    'nav.guided-tours':'Průvodcovské prohlídky',
    'nav.gold-label':'Gold Label',
    'nav.extras':'Katalog doplňků',
    'nav.after-dark':'Praha po setmění',
    'nav.col.guest':'Zážitek hosta',
    'nav.concierge':'Digitální concierge',
    'nav.by-passion':'Praha podle vášně',
    'nav.corporate':'Skupiny a firmy',
    'nav.for-hotels':'Pro hotely',
    'nav.col.strategy':'Strategie a příjmy',
    'nav.business-plan':'Podnikatelský plán',
    'nav.analytics':'Analytika',
    'nav.col.operations':'Provoz a důvěra',
    'nav.integration':'Integrace',
    'nav.social-proof':'Reference',
    'nav.partnership':'Partnerství →',
    'nav.badge.premium':'Prémiové',
    /* FOOTER */
    'footer.desc':'Navrhované partnerství přinášející kurátorské průvodcovské prohlídky a prémiové zážitky hostů do všech 28 hotelů Czech Inn Hotels v Praze.',
    'footer.address':'Hybernská 24, Praha 1 — 110 00',
    'footer.stats':'28 hotelů · 3 300+ pokojů',
    'footer.col.experiences':'Zážitky',
    'footer.col.tools':'Nástroje pro hosty',
    'footer.col.hotels':'Pro hotely',
    'footer.guided-tours':'Průvodcovské prohlídky',
    'footer.gold-label':'Gold Label',
    'footer.extras':'Katalog doplňků',
    'footer.after-dark':'Praha po setmění',
    'footer.corporate':'Skupiny a firmy',
    'footer.concierge':'Digitální concierge',
    'footer.by-passion':'Praha podle vášně',
    'footer.integration':'Hotelová integrace',
    'footer.business-plan':'Podnikatelský plán',
    'footer.analytics':'Analytika',
    'footer.social-proof':'Reference',
    'footer.partnership':'Partnerství →',
    'footer.tagline':'Platforma průvodcovských zážitků — navrženo pro',
    'footer.prepared':'Připraveno pro',
    'footer.sub':'Všechny prohlídky, průvodci a ceny jsou reálné a připravené k nasazení.',
    'float.cta':'Zahájit partnerství →',
    /* INDEX */
    'idx.eyebrow':'Czech Inn Hotels × UNO',
    'idx.hero.title':'Hosté v Praze utrácejí miliony za zážitky.<br><em>Nic z toho nejde do Czech Inn Hotels.</em>',
    'idx.hero.sub':'Každou noc přijíždí do vašich hotelů 3 300 hostů. Většina si zážitky zarezervuje, než Prahu opustí — jen ne přes vás. Zatím.',
    'idx.cta.primary':'Zobrazit plán partnerství',
    'idx.cta.secondary':'Prozkoumat zážitky',
    'idx.stat1.label':'Partnerských hotelů',
    'idx.stat2.label':'Pokojů v dosahu',
    'idx.stat3.label':'Prohlídek připraveno',
    'idx.stat4.label':'Průměrné hodnocení hostů',
    'idx.why.eyebrow':'Proč to funguje',
    'idx.why.title':'Nejoblíbenější hotelová skupina v Praze. Nejdůvěryhodnější provozovatel prohlídek v Praze.',
    'idx.rev.eyebrow':'Dopad na příjmy',
    'idx.rev.title':'Skutečná čísla. Skutečná příležitost.',
    'idx.exp.eyebrow':'Balík zážitků',
    'idx.exp.title':'Každý host. Každá nálada. Každý okamžik.',
    /* AFTER DARK */
    'ad.eyebrow':'Czech Inn Hotels × UNO',
    'ad.title':'Praha<br><em>po setmění</em>',
    'ad.sub':'Když skončí denní prohlídky, začíná skutečná Praha. Verze, kterou většina turistů nikdy nenajde — jazzové sklepy, střešní bary s výhledem na hrad, legendární koktejlové bary a divadla, která nikde jinde na světě neexistují.',
    'ad.tab.jazz':'Jazz a live',
    'ad.tab.rooftop':'Střešní terasy',
    'ad.tab.cocktail':'Koktejlové bary',
    'ad.tab.shows':'Představení',
    'ad.tab.hidden':'Skrytá místa',
    'ad.filter.all':'Vše',
    'ad.filter.budget':'€ Levné',
    'ad.filter.mid':'€€ Střední',
    'ad.filter.premium':'€€€ Prémiové',
    'ad.filter.walkin':'Bez rezervace',
    'ad.filter.book':'Rezervace nutná',
    'ad.routes.eyebrow':'Kurátorské večery',
    'ad.routes.title':'Tři večery, tři nálady.',
    'ad.routes.cta':'Rezervovat tuto trasu →',
    'ad.build.title':'Sestavte si večer',
    'ad.build.sub':'Vyberte až 3 místa',
    'ad.build.cta':'Rezervovat přes concierge →',
    'ad.build.clear':'Vymazat',
    'ad.practical.eyebrow':'Před odchodem',
    'ad.practical.title':'Co je dobré vědět',
    /* CONCIERGE */
    'dc.eyebrow':'Platforma pro zážitky hostů',
    'dc.title':'Concierge, kterého si každý host<br><em>přál ve vašem hotelu</em>',
    'dc.sub':'Vaši hosté přijíždějí s vysokými očekáváními. Odjíždějí a mluví o městě — protože jsme Prahu udělali osobní, kurátorskou a bezproblémovou.',
    'dc.cta':'Vyzkoušet concierge',
    /* TOURS */
    'tours.eyebrow':'4 prohlídky · 12 jazyků · hodnocení 4,91★',
    'tours.title':'Čtyři příběhy Prahy,<br><em>jak je ještě nikdo nevyprávěl</em>',
    'tours.sub':'Každá zastávka vybrána záměrně. Každý příběh vyprávěn někým, kdo zde strávil celý život. Každá prohlídka hodnocena 4,91 hvězdičkami hosty, kteří se vrátili do hotelu a vyprávěli.',
    'tours.cta':'Rezervovat prohlídku',
    /* GOLD LABEL */
    'gl.eyebrow':'Czech Inn Hotels — prémiová úroveň',
    'gl.title':'Gold<br><em>Label</em>',
    'gl.sub':'Kurátorské. Soukromé. Nezapomenutelné.',
    /* EXTRAS */
    'ex.eyebrow':'Zážitky Czech Inn Hotels',
    'ex.title':'26 zážitků <em>na které Praha nezapomene</em>',
    'ex.sub':'26 pečlivě vybraných pražských zážitků — od soukromých kurzů vaření po helikoptérové lety. Od €29 do €249. Rezervujte jednotlivě nebo spolu s prohlídkou.',
    /* BUSINESS PLAN */
    'bp.eyebrow':'Podnikatelský plán',
    'bp.title':'Podnikatelský plán —<br><em>Czech Inn Hotels</em><br>Platforma průvodcovských zážitků',
    'bp.sub':'Konzervativní prognózy. Ověřený model. Připraveno k nasazení.',
    /* PARTNERSHIP */
    'pp.eyebrow':'Partnerství',
    'pp.title':'Partnerství, které se<br><em>zaplatí samo</em> — ještě před<br>prvním výdajem',
    'pp.sub':'28 hotelů. 3 300 pokojů. Každý host přijíždí do Prahy s penězi na zážitky — a nemá kde je utratit. Zatím.',
    'pp.cta':'Zahájit rozhovor',
    /* BY PASSION */
    'byp.eyebrow':'Czech Inn Hotels',
    'byp.title':'Praha <em>podle vášně</em>',
    'byp.sub':'Odpovězte na čtyři otázky. Získejte osobní pražský itinerář sestavený kolem toho, co skutečně milujete — ne co dělá každý.',
    /* CORPORATE */
    'corp.eyebrow':'Skupiny a firmy',
    'corp.title':'Když váš tým opustí Prahu,<br><em>odejde jiný.</em>',
    'corp.sub':'Nejjednodušší brief, který váš asistent kdy pošle. Incentivní zájezdy, teambuilding, retreaty a prodloužení konferencí — od 10 do 200 osob, vše v Czech Inn Hotels.',
    /* INTEGRATION */
    'int.eyebrow':'Hotelová integrace',
    'int.title':'Nulové tření.<br><em>Žádné výpadky.</em>',
    'int.sub':'Celá platforma se integruje s provozem vašeho hotelu za méně než 30 dní — bez narušení PMS, bez dedikovaného IT zdroje, bez přeškolení personálu.',
    /* ANALYTICS */
    'an.eyebrow':'Výkonnostní přehled',
    'an.title':'Čísla, která vám řeknou<br><em>přesně, o co přicházíte</em>',
    'an.sub':'Reálná data z pražského cestovního ruchu 2024. Projektovaná data modelovaná na obsazenosti Czech Inn Hotels a srovnatelných benchmarcích. Všechny zdroje jsou uvedeny.',
    /* SOCIAL PROOF */
    'sp.eyebrow':'Ověřeno hosty',
    'sp.title':'847 hostů. 4,91 hvězdiček.<br><em>A toto skutečně řekli.</em>',
    'sp.sub':'412 ověřených recenzí. 847 prohlídek dokončených v roce 2024. Platforma, kterou hosté doporučují přátelům — a která přináší opakované rezervace.',
    /* COMMON */
    'cta.concierge':'Rezervovat přes concierge →',
    'cta.learn-more':'Zjistit více →',
    'cta.view-all':'Zobrazit vše →',
    'cta.partnership':'Zahájit partnerství →',
    'label.new':'Nové',
    'label.popular':'Oblíbené',
    'label.premium':'Prémiové',
    'label.free':'Zdarma',
  }
};

function applyLang(code) {
  const t = T[code] || T.en;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const v = t[el.dataset.i18n];
    if (v !== undefined) el.textContent = v;
  });
  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const v = t[el.dataset.i18nHtml];
    if (v !== undefined) el.innerHTML = v;
  });
  const isRTL = code === 'he';
  document.documentElement.setAttribute('dir', isRTL ? 'rtl' : 'ltr');
  document.documentElement.setAttribute('lang', code);
  document.querySelectorAll('.nav-lang-btn').forEach(b =>
    b.classList.toggle('active', b.dataset.lang === code)
  );
  localStorage.setItem('lang', code);
}

document.addEventListener('DOMContentLoaded', () => {
  const saved = localStorage.getItem('lang');
  const urlLang = new URLSearchParams(window.location.search).get('lang');
  applyLang(urlLang || saved || 'en');

  document.addEventListener('click', e => {
    const btn = e.target.closest('[data-lang]');
    if (btn && T[btn.dataset.lang]) applyLang(btn.dataset.lang);
  });
});
